export const FETCH_MOVIE_DETAILS="FETCH_MOVIE_DETAIL_REQUEST";
export const FETCH_MOVIE_SUCCESS="FETCH_MOVIE_DETAIL_SUCCESS";
export const FETCH_MOVIE_FAILURE="FETCH_MOVIE_DETAIL_FAILURE";



// - = Id
// _= CSS
